---
title: "Data Analysis: Assignment: 1"
author: "Ghazal and Shah Ali"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---


```{r include=FALSE}
# Libraries
rm(list=ls())

library(tidyverse)
library(lspline)
library(cowplot)
library(boot)
library(estimatr)
library(huxtable)
library(stargazer)
library(modelsummary)

```

```{r}

data_all <- read_csv(paste0("/Users/ghazalayobi/Downloads/morg-2014-emp.csv"), 
                     col_types = cols(.default = "?", 
                                      state = "c"))
```

```{r echo=TRUE, warning=FALSE}

data <- data_all %>% filter(occ2012==0136)

data <- data %>% mutate(female=as.numeric(sex==2)) %>%
  mutate(w=earnwke/uhours) %>%
  mutate(lnw=log(w)) %>%
  mutate(grade92sq=grade92^2)

data %>% dplyr::select(earnwke,uhours,w) %>% summary()

data %>% filter(w>=1) %>% dplyr::select(earnwke,uhours,w) %>% summary()

tabulate(data$female)
table(data$occ2012,data$female)


```

```{r echo=TRUE, warning=FALSE}
reg1<-lm(lnw~female,data) 
summary(reg1)

reg2 <- lm_robust(lnw ~ female, data = data, se_type = "HC1")
summary(reg2)

msummary(list(reg1, reg2),
         fmt="%.4f",
         gof_omit = 'DF|Deviance|Log.Lik.|F|R2 Adj.|AIC|BIC',
         stars=c('*' = .05, '**' = .01)
)

```

```{r echo=TRUE, warning=FALSE}
#Unconditional

reg3 <- lm_robust(lnw ~ grade92, data = data, se_type = "HC1")
reg3

# 
reg4 <- lm_robust(lnw ~ grade92+grade92sq, data = data, se_type = "HC1")
reg4
unique(data$grade92)
# 39 - 46 grades
reg5 <- lm_robust(lnw ~ lspline(grade92, c(42,46)), data = data, se_type = "HC1")
reg5

gm <-  c('R2' = 'R-squared (%)',
         'se_type' = 'SE type')

cm <- c('R2' = 'R-squared (%)',
        'lspline(grade92, c(42, 46))2' = 'spline(grade92, c(38,41))',
        '(Intercept)' = 'Constant')

msummary(list(reg1, reg2, reg3, reg4, reg5),
         fmt="%.3f",
         gof_omit = 'DF|Deviance|Log.Lik.|F|R2 Adj.|AIC|BIC',
         stars=c('*' = .05, '**' = .01),
         coef_rename = cm,
         #output = paste(output,"ch09_reg2-R.tex",sep="")
)
```

```{r echo=TRUE, warning=FALSE}
#lowess
reg6 <- loess(lnw ~ grade92, data, control = loess.control(surface = "direct"))
summary(reg6)

loess(lnw ~ grade92, data)
```

```{r echo=TRUE, warning=FALSE}
##############################
# graphs
##############################

graph1 <- ggplot(data = data, aes(x = grade92, y = lnw)) +
  geom_point(color = "#3a5e8cFF") + 
  geom_smooth(method="loess", color = "#10a53dFF") +
  scale_x_continuous(expand=c(0.01, 0.01), limits = c(37, 47),   breaks=seq(37, 47,   by=1)) + 
  scale_y_continuous(expand=c(0.01, 0.01),limits = c(1.5, 4.5), breaks=seq(1.5, 4.5, by=0.50)) +
  labs(x = "grade92 (years)",y = "ln(earnings per hour)")+
  theme_light() 
graph1


graph2 <- ggplot(data = data, aes(x = grade92, y = lnw)) +
  geom_point(color = "#3a5e8cFF") + 
  geom_smooth(method="loess", color = "#10a53dFF") +
  scale_x_continuous(expand=c(0.01, 0.01), limits = c(42, 47),   breaks=seq(37, 47,   by=1)) + 
  scale_y_continuous(expand=c(0.01, 0.01),limits = c(1.5, 4.5), breaks=seq(1.5, 4.5, by=0.50)) +
  labs(x = "grade92 (years)",y = "ln(earnings per hour)")+
  theme_light() 
graph2

```

```{r echo=TRUE}

#####################################
# bootstrap
#####################################

set.seed(201711)

# function to obtain regression weights
bs <- function(formula, data, indices) {
  d <- data[indices,] # allows boot to select sample
  fit <- lm(formula, data=d)
  return(coef(fit))
}

# bootstrapping with 1000 replications
results <- boot(data=data, statistic=bs,
                R=1000, formula=lnw~female)

b_earnings_female <- as.data.frame(results$t)
colnames(b_earnings_female) <- c('_b_intercept','_b_female')


bstps<- ggplot(data=b_earnings_female, aes(`_b_female`)) +
  geom_histogram(aes(y = (..count..)/sum(..count..)), binwidth = 0.025,  center=0.0125, closed="left", 
                 color = "#3a5e8cFF" , fill = "#3a5e8cFF",
                 size = 0.2, alpha = 0.8,  show.legend=F, na.rm=TRUE) +
  geom_segment(aes(x = -0.21, y = 0, xend = -0.21, yend = 0.2), color = "#10a53dFF", size = 1)+
  annotate("text", x = -0.18, y = 0.19, label = "mean", size=2.5) +
  coord_cartesian(xlim = c(-0.4, 0), ylim = c(0, 0.2)) +
  labs(x = "Slope coefficients from bootstrap samples",y = "Percent")+
  scale_y_continuous(expand = c(0.0,0.0), limits = c(0,0.2), 
                     labels = scales::percent_format(accuracy = 1)) +
  theme_light() 
bstps



```

