---
title: "Data Analysis: Assignment: 1"
author: "Ghazal and Shah Ali"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---


```{r include=FALSE}
# Libraries
rm(list=ls())

library(tidyverse)
library(modelsummary)
library(fixest)
library(dplyr)
library(kableExtra)
library(huxtable)
library(data.table)
library(stargazer)
library(haven)
library(estimatr)
library(boot)

```

```{r include=FALSE}
# Importing data
#data_all <- read_csv("https://osf.io/4ay9x/download")

data_all <- read_csv(paste0("/Users/ghazalayobi/Downloads/morg-2014-emp.csv"), 
                     col_types = cols(.default = "?", 
                                      state = "c"))
```

```{r warning=FALSE, include=FALSE}
# Filters and Data Transformations

data <- data_all %>% filter(occ2012==800)
data <-  data.table(data)

data <- data %>% mutate(female=as.numeric(sex==2)) %>% 
  mutate(w=earnwke/uhours) %>%
  mutate(lnw=log(w))

data <- data %>% filter(grade92 >= 41)

data$gender <- as.numeric(data$sex)
data$gender[data$gender==1] <- "Male"
data$gender[data$gender==2] <- "Female"
data$gender <- as.character(data$gender)


```


```{r echo=FALSE, fig.align = 'left'}

# Observations
data[, .N, by = data$gender] %>% kbl(caption = "Table : 1")  %>% kable_classic(full_width=F)
```


```{r echo=FALSE}
# Summary

P95 <- function(x){ quantile(x,.95,na.rm=T)}
datasummary((`Weekly earnings` = earnwke) + (`Weekly hours worked` = uhours) + w + lnw ~ Mean + SD + Min + Max + Median + P95 + N, data = data, title = "Table : 2", )


```

```{r include=FALSE}
data <- data %>% filter(w >=1)
```

```{r echo=FALSE, fig.height=4, fig.width=4}

figure1 <- ggplot(data = data, aes(x = w)) + 
  geom_density(color = "#3a5e8cFF") + 
  ggtitle("Figure : 1") + 
  theme_light() +
  labs(x = "Wage",y = "Density")

figure2 <- ggplot(data = data, aes(x = lnw)) + 
  geom_density(color = "#3a5e8cFF") + 
  ggtitle("Figure : 2") + 
  theme_light() +
  labs(x = "Log of Wage",y = "Density")
figure1
figure2
```


```{r message=FALSE, warning=FALSE, include=FALSE, fig.align = 'left'}

reg1 <- lm(w~female, data)
reg2 <- lm(lnw~female,data) 


```


```{r echo=FALSE, message=FALSE, warning=FALSE}

msummary(list("Wage (LM)" = reg1, "Log Wage (LM)" = reg2),
         fmt="%.4f",
         gof_omit = 'DF|Deviance|Log.Lik.|F|R2 Adj.|AIC|BIC|R2 Pseudo|R2 Within',
         stars=c('*' = .05, '**' = .01),
         title = "Table : 3"
)

```



```{r message=FALSE, warning=FALSE, include=FALSE}


data <- data %>% mutate(
  ed_Associate_voc=as.numeric(grade92==41),
  ed_Associate_ap=as.numeric(grade92==42),
  ed_BA=as.numeric(grade92==43),
  ed_MA=as.numeric(grade92==44),
                      ed_Profess = as.numeric(grade92==45),
                      ed_PhD = as.numeric(grade92==46))



reg3 <- lm_robust(lnw ~ female, data=data, se_type = "HC1")

reg4 <- lm_robust(lnw ~ female + grade92, data = data)
# Base is ed_Associate_voc
reg5 <- lm_robust(lnw ~ female + ed_Associate_ap +ed_BA + ed_MA + ed_Profess + ed_PhD, data = data, se_type = "HC1")


# Base is ed_Associate_ap
reg6 <- lm_robust(lnw ~ female + ed_Associate_voc +ed_BA + ed_MA + ed_Profess + ed_PhD, data=data, se_type = "HC1")

# Base is ed_BA
reg7 <- lm_robust(lnw ~ female + ed_Associate_voc + ed_Associate_ap + ed_MA + ed_Profess + ed_PhD, data=data, se_type = "HC1")

# Base is ed_MA
reg8 <- lm_robust(lnw ~ female + ed_Associate_voc + ed_Associate_ap + ed_BA + ed_Profess + ed_PhD, data=data, se_type = "HC1")

# Base is ed_Profess
reg9 <- lm_robust(lnw ~ female + ed_Associate_voc + ed_Associate_ap + ed_BA + ed_MA + ed_PhD, data=data, se_type = "HC1")

# Base is ed_PhD
reg10 <- lm_robust(lnw ~ female + ed_Associate_voc + ed_Associate_ap + ed_BA + ed_MA + ed_Profess, data=data, se_type = "HC1")


```

```{r echo=FALSE, warning=FALSE, message=FALSE}

msummary(list(reg3, reg4, reg5),
         fmt="%.4f",
         gof_omit = 'DF|Deviance|Log.Lik.|F|R2 Adj.|AIC|BIC|R2 Pseudo|R2 Within|Std.Errors',
         stars=c('*' = .05, '**' = .01),
         title = "Table : 4"
         )

```


```{r warning=FALSE, include=FALSE}
# Interaction between gender and education levels



reg11 <- lm_robust(lnw ~ grade92 + ed_Associate_ap + ed_BA + ed_MA + ed_Profess + ed_PhD, data=data %>% filter(female==1), se_type = "HC1")

reg12 <- lm_robust(lnw ~ grade92 + ed_Associate_ap + ed_BA + ed_MA + ed_Profess + ed_PhD, data = data %>% filter(female==0), se_type = "HC1")

reg13 <- lm_robust(lnw ~ grade92 + female + female*ed_Associate_ap + female*ed_BA + female*ed_MA + female*ed_Profess + female*ed_PhD, data=data, se_type = "HC1")


```

```{r echo=FALSE, message=FALSE, warning=FALSE}

# problem

msummary(list("Women (log Wage)" = reg11, "Men (log Wage)" = reg12, "All (log Wage)" = reg13),
         fmt="%.4f",
         gof_omit = 'DF|Deviance|Log.Lik.|F|R2 Adj.|AIC|BIC|R2 Pseudo|R2 Within|Std.Errors',
         stars=c('*' = .05, '**' = .01),
         title = "Table : 5"
         )
```


```{r echo=FALSE, message=FALSE, warning=FALSE, fig.height=4, fig.width=4}
##############################
# graphs
##############################

graph1 <- ggplot(data = data, aes(x = grade92, y = lnw)) +
  geom_point(color = "#3a5e8cFF") + 
  geom_smooth(method="loess", color = "#10a53dFF", formual = 'y ~ x') +
  scale_x_continuous(expand=c(0.01, 0.01), limits = c(40.5, 46.5),   breaks=seq(40, 47,   by=1)) + 
  scale_y_continuous(expand=c(0.01, 0.01),limits = c(1.5, 4.5), breaks=seq(1.5, 4.5, by=0.50)) +
  labs(x = "Grade92 (Education Levels)",y = "ln(earnings per hour)")+
  theme_light() +
  ggtitle("Figure 1")
graph1

graph2 <- ggplot(data = data, aes(x = grade92, y = lnw)) +
  geom_point(color = "#3a5e8cFF") + 
  geom_smooth(method="lm", color = "#10a53dFF", formual = 'y ~ x') +
  scale_x_continuous(expand=c(0.01, 0.01), limits = c(40.5, 46.5),   breaks=seq(40, 47,   by=1)) + 
  scale_y_continuous(expand=c(0.01, 0.01),limits = c(1.5, 4.5), breaks=seq(1.5, 4.5, by=0.50)) +
  labs(x = "Grade92 (Education Levels)",y = "ln(earnings per hour)")+
  theme_light() +
  ggtitle("Figure 2")
graph2


```


```{r eval=FALSE, include=FALSE}

#####################################
# bootstrap
#####################################

set.seed(201711)

# function to obtain regression weights
bs <- function(formula, data, indices) {
  d <- data[indices,] # allows boot to select sample
  fit <- lm(formula, data=d)
  return(coef(fit))
}

# bootstrapping with 1000 replications
results <- boot(data=data, statistic=bs,
                R=1000, formula=lnw~female)

b_earnings_female <- as.data.frame(results$t)
colnames(b_earnings_female) <- c('_b_intercept','_b_female')


bstps<- ggplot(data=b_earnings_female, aes(`_b_female`)) +
  geom_histogram(aes(y = (..count..)/sum(..count..)), binwidth = 0.025,  center=0.0125, closed="left", 
                 color = "#3a5e8cFF" , fill = "#3a5e8cFF",
                 size = 0.2, alpha = 0.8,  show.legend=F, na.rm=TRUE) +
  geom_segment(aes(x = -0.19, y = 0, xend = -0.19, yend = 0.35), color = "#10a53dFF", size = 1)+
  annotate("text", x = -0.18, y = 0.35, label = "mean", size=2.5) +
  coord_cartesian(xlim = c(-0.3, 0), ylim = c(0, 0.4)) +
  labs(x = "Slope coefficients from bootstrap samples",y = "Percent")+
  scale_y_continuous(expand = c(0.0,0.0), limits = c(0,0.5), 
                     labels = scales::percent_format(accuracy = 1)) +
  theme_light() 
bstps


```

